In [1]:
import pandas as pd
import numpy as np

arr=np.array([1,2,3,4])
print(arr)

s=pd.Series(arr)
print(s)
print(type(s))

[1 2 3 4]
0    1
1    2
2    3
3    4
dtype: int64
<class 'pandas.core.series.Series'>


In [5]:
print(s[0:5])
a=pd.Series(['a','b','c'])
print(a)
print(type(a))

0    1
1    2
2    3
3    4
dtype: int64
0    a
1    b
2    c
dtype: object
<class 'pandas.core.series.Series'>


In [7]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
df=pd.DataFrame(arr)
print(df)

temp=np.random.randint(low=20,high=100,size=[20,])
name=np.random.choice(['Abhay','Teclov','Geekshub','Ankit'],20)
random=np.random.choice([10,11,13,12,14],20)
df=pd.DataFrame({"Temp":temp,"Name":name,"Random":random})
print(df)

[[1 2 3]
 [4 5 6]]
   0  1  2
0  1  2  3
1  4  5  6
    Temp      Name  Random
0     24     Ankit      11
1     25     Abhay      10
2     31  Geekshub      12
3     87     Abhay      13
4     66  Geekshub      13
5     30    Teclov      11
6     20    Teclov      12
7     57    Teclov      14
8     69  Geekshub      13
9     80    Teclov      14
10    90     Abhay      13
11    79    Teclov      10
12    67    Teclov      10
13    88    Teclov      12
14    73  Geekshub      14
15    47     Abhay      12
16    66     Ankit      10
17    41    Teclov      11
18    24  Geekshub      12
19    51     Abhay      10


In [9]:
print(type(df))
print(df.head())
print(df.tail())

<class 'pandas.core.frame.DataFrame'>
   Temp      Name  Random
0    24     Ankit      11
1    25     Abhay      10
2    31  Geekshub      12
3    87     Abhay      13
4    66  Geekshub      13
    Temp      Name  Random
15    47     Abhay      12
16    66     Ankit      10
17    41    Teclov      11
18    24  Geekshub      12
19    51     Abhay      10


In [21]:
print(df.shape)
print(df.columns)
print(df['Temp'].describe())
print(df.info())
print(df.values)
print(df.set_index('Temp',inplace=True))
print(df.sort_index(axis=0,ascending=False))
print(df.sort_values(by='Random',ascending=False))
print(df.drop(['Random'],axis=1))

(20, 3)
Index(['Temp', 'Name', 'Random'], dtype='object')
count    20.000000
mean     55.750000
std      24.019455
min      20.000000
25%      30.750000
50%      61.500000
75%      74.500000
max      90.000000
Name: Temp, dtype: float64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Temp    20 non-null     int64 
 1   Name    20 non-null     object
 2   Random  20 non-null     int64 
dtypes: int64(2), object(1)
memory usage: 612.0+ bytes
None
[[24 'Ankit' 11]
 [25 'Abhay' 10]
 [31 'Geekshub' 12]
 [87 'Abhay' 13]
 [66 'Geekshub' 13]
 [30 'Teclov' 11]
 [20 'Teclov' 12]
 [57 'Teclov' 14]
 [69 'Geekshub' 13]
 [80 'Teclov' 14]
 [90 'Abhay' 13]
 [79 'Teclov' 10]
 [67 'Teclov' 10]
 [88 'Teclov' 12]
 [73 'Geekshub' 14]
 [47 'Abhay' 12]
 [66 'Ankit' 10]
 [41 'Teclov' 11]
 [24 'Geekshub' 12]
 [51 'Abhay' 10]]
None
          Name  Random
Temp                  
90    

In [27]:
print(df.head())
print(df.iloc[[0,1]])
print(df.iloc[1:3,1])
print(df.loc[df.Random>13])
print(df.loc[(df.Random>13)|(df.Random==10),:])


          Name  Random
Temp                  
24       Ankit      11
25       Abhay      10
31    Geekshub      12
87       Abhay      13
66    Geekshub      13
       Name  Random
Temp               
24    Ankit      11
25    Abhay      10
Temp
25    10
31    12
Name: Random, dtype: int64
          Name  Random
Temp                  
57      Teclov      14
80      Teclov      14
73    Geekshub      14
          Name  Random
Temp                  
25       Abhay      10
57      Teclov      14
80      Teclov      14
79      Teclov      10
67      Teclov      10
73    Geekshub      14
66       Ankit      10
51       Abhay      10


In [29]:
# merging & concat
d1=pd.DataFrame([['a',1],['b',2]],columns=['col1','number'])
d2=pd.DataFrame([['c',3],['d',4]],columns=['letter','number'])
print(d1)
print(d2)
print(pd.concat([d1,d2],axis=0))
print(pd.concat([d1,d2],axis=0,ignore_index=True))
print(pd.concat([d1,d2],axis=1))


  col1  number
0    a       1
1    b       2
  letter  number
0      c       3
1      d       4
  col1  number letter
0    a       1    NaN
1    b       2    NaN
0  NaN       3      c
1  NaN       4      d
  col1  number letter
0    a       1    NaN
1    b       2    NaN
2  NaN       3      c
3  NaN       4      d
  col1  number letter  number
0    a       1      c       3
1    b       2      d       4


In [3]:
import pandas as pd
d1 = pd.DataFrame({
"city" : ["lucknow","kanpur","agra","delhi"],
"temperature" : [32,45,30,40]
})
print(d1)
d2 = pd.DataFrame({
"city" : ["delhi","lucknow","kanpur"],
"humidity" : [68,65,75]
})
print(d2)


      city  temperature
0  lucknow           32
1   kanpur           45
2     agra           30
3    delhi           40
      city  humidity
0    delhi        68
1  lucknow        65
2   kanpur        75


In [7]:
df=pd.merge(d1,d2,on='city')
print(df)
df=pd.merge(d1,d2,on='city',how='outer')
print(df)
df=pd.merge(d1,d2,on='city',how='left')
print(df)

      city  temperature  humidity
0  lucknow           32        65
1   kanpur           45        75
2    delhi           40        68
      city  temperature  humidity
0     agra           30       NaN
1    delhi           40      68.0
2   kanpur           45      75.0
3  lucknow           32      65.0
      city  temperature  humidity
0  lucknow           32      65.0
1   kanpur           45      75.0
2     agra           30       NaN
3    delhi           40      68.0


In [1]:
import pandas as pd
x=pd.Series(range(10,20))
print(x)
y=pd.Series([2,1,4,5,8,12,18,25,96,48])
print(y)

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64
0     2
1     1
2     4
3     5
4     8
5    12
6    18
7    25
8    96
9    48
dtype: int64


In [3]:
print(x.corr(y)) #pearsons r

0.7586402890911867


In [5]:
print(y.corr(x))

0.7586402890911869


In [7]:
print(x.corr(y,method='spearman'))
print(x.corr(y,method='kendall'))

0.9757575757575757
0.911111111111111
